### ISSUE TITLE
Failing validation of sensor status

### ISSUE THREAD

**Issue by evilB** [woutercoppens/pyhaopenmotics-v2#247]
# Problem/Motivation

A sensor failed in my installation resulting in a null value for status for the sensor.
This library fails the validation of input data leading to the failure of loading the homeassistant plugin.

The documentation of the API is ambiguous 
[openmotics api documentation](https://postman.openmotics.com/#aa9106de-a61f-4e80-b5c0-915c1a1fb51b)

The examples on the right only contain null values for status.

The example object does not explicitely state that the status can be null. 

I've reached out to openmotics via e-mail and Felix confirmed that status can indeed be null.

```
// example object
{
    "_version": <version>,
    "id": <id>,
    "name": "<name>",
    "location": {
        "room_id": null | <room_id>,
        "installation_id": <installation id>
    },
    **"status": {
        "humidity": null | <hunidity 0 - 100>,
        "temperature": null | <temperature -32 - 95>,
        "brightness": null | <brightness 0 - 100>
    }**
}
// example response 
{
  "data": [
    {
      "name": "Sensor 0",
      **"status": null,**
      "location": {
        "installation_id": 1,
        "room_id": null
      },
      "id": 4,
      "local_id": 0,
      "physical_quantity": "humidity",
      "unit": "percent",
      "_version": 1.1
    }, ...]


```

## Expected behavior

Library handles null value of a sensor status.
Like the examples responses.

## Actual behavior

Library fails with a validation error as it expects the example object

## Steps to reproduce

Try and parse the example responses without validation errors. 

## Proposed changes

https://github.com/woutercoppens/pyhaopenmotics-v2/compare/main...evilB:pyhaopenmotics-v2:main

I've tried to setup my own version of the homeassistant plugin with my fork of the pyhaopenmotics lib, but i couldn't get the whole toolchain to work. (Poetry failed with obscure errors etc..) So this change is completely untested.

**Comment by woutercoppens** [comment]
Are you using the official repositories?
https://github.com/openmotics/pyhaopenmotics
https://github.com/openmotics/home-assistant

You filed a bugreport in my private repos. I use these for testing and experimenting. These are often broken.

**Comment by evilB** [comment]
> You filed a bugreport in my private repos. I use these for testing and experimenting. These are often broken.

oops.

I'm not sure if I use the official repo at home or not. I will check tonight.
